stages: 
    - build
    - test
    - deploy

build website: 
    image: node:16-alpine
    stage: build
    script: 
        - yarn install
        - yarn lint
        - yarn test
        - yarn build
    artifacts:
        paths:
            - build


test website:
    image: node:16-alpine
    stage: test
    script:
        - yarn global add serve
        - apk add curl
        - serve -s build &
        - sleep 20
        - curl http://localhost:3000 | grep "React App"
        - npm install

deploy to heroku:
    stage: deploy
    before_script:
        - npm install --global surge
    script:
        - surge --project ./public --domain https://$PRODUCTION_DOMAIN


